services:
  - type: web
    name: login-api
    env: docker
    plan: free
    rootDir: backend
    dockerfilePath: Dockerfile
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: PORT
        value: 4000
      - key: MONGO_URI
        sync: false # set in Render dashboard (e.g., mongodb+srv://...)
      - key: JWT_SECRET
        sync: false # set in Render dashboard to a long random string
      - key: CLIENT_ORIGIN
        value: https://abdul-1432.github.io/resume-optimizer-ai/
